from __future__ import annotations

from pathlib import Path

from lib.cli_introspector import generate_command_graph
from lib.atomic_write import safe_write


OUTPUT_DIR = Path(
    "docs-generated/use-cases"
)


def build_use_cases(commands):

    use_cases = {}

    for command in commands:

        meta = command["metadata"]

        for use_case in meta.get(
            "use_cases",
            []
        ):

            use_cases.setdefault(
                use_case,
                []
            ).append(command)

    return use_cases


def render_use_case(
    name: str,
    commands: list[dict],
):

    lines = [
        f"# {name}",
        "",
        "## Goal",
        "",
        f"This guide explains how to accomplish the **{name}** workflow using ProjectBrain.",
        "",
        f"**Commands Involved:** {len(commands)}",
        "",
        "---",
        "",
        "## Recommended Commands",
        "",
        "| Command | Description | Category |",
        "|----------|-------------|----------|",
    ]

    for command in commands:

        description = (
            command["help"]
            .splitlines()[0]
            .strip()
        )

        category = (
            command["metadata"]
            .get("category", "-")
        )

        lines.append(
            f"| `{command['command']}` | {description} | {category} |"
        )

    lines.extend(
        [
            "",
            "---",
            "",
            "## Recommended Workflow",
            "",
        ]
    )

    # Try to find a command in this use case that defines a 'workflow'
    primary_workflow = []
    for command in commands:
        if command["metadata"].get("workflow"):
            primary_workflow = command["metadata"]["workflow"]
            break

    if primary_workflow:
        for index, step in enumerate(primary_workflow, start=1):
            # Check if step is a known command
            cmd_info = next((c for c in commands if c["command"] == step), None)
            step_desc = cmd_info["help"].splitlines()[0] if cmd_info else "Follow the prompt."
            
            lines.extend([
                f"### Step {index}",
                "",
                f"Run:",
                "",
                f"```bash",
                step,
                f"```",
                "",
                step_desc,
                "",
            ])
    else:
        # Fallback to listing all commands if no specific workflow is defined
        for index, command in enumerate(
            commands,
            start=1,
        ):
            lines.extend(
                [
                    f"### Step {index}",
                    "",
                    f"Run:",
                    "",
                    f"```bash",
                    command["command"],
                    f"```",
                    "",
                    command["help"].splitlines()[0],
                    "",
                ]
            )

    lines.extend(
        [
            "---",
            "",
            "## Expected Outcome",
            "",
            f"After completing the **{name}** workflow you should have all required outputs generated by the commands above.",
            "",
            "## Related Workflows",
            "",
        ]
    )

    related = set()

    for command in commands:

        for use_case in (
            command["metadata"]
            .get("use_cases", [])
        ):

            if use_case != name:
                related.add(use_case)

    if related:

        for item in sorted(related):

            lines.append(
                f"- {item}"
            )

    else:

        lines.append(
            "_No related workflows._"
        )

    return "\n".join(lines)


def main():

    OUTPUT_DIR.mkdir(
        parents=True,
        exist_ok=True,
    )

    commands = generate_command_graph()

    use_cases = build_use_cases(
        commands
    )

    success = True
    for name, items in use_cases.items():

        filename = (
            name.lower()
            .replace(" ", "_")
            + ".md"
        )

        output_file = (
            OUTPUT_DIR /
            filename
        )

        if not safe_write(
            output_file,
            render_use_case(
                name,
                items,
            ),
        ):
            success = False

    if not success:
        raise SystemExit(1)


if __name__ == "__main__":
    main()
